services:
  wazuh-user:
    image: busybox
    restart: on-failure
    volumes:
      - /:/host:ro
    entrypoint:
      - chroot
      - /host
      - sh
      - -c
      - id wazuh || useradd wazuh

  wazuh-agent:
    image: wazuh-agent
    build: ..
    depends_on:
      wazuh-user:
        condition: service_started
    restart: unless-stopped
    privileged: true
    pid: host
    ipc: host
    network_mode: host
    userns_mode: host
    environment:
      WAZUH_MANAGER_ADDRESS:
      WAZUH_RULESET_SCA: cis_ubuntu18-04
    volumes:
      - /:/host:ro
      - /var/ossec:/host/var/ossec
      - ./authd.pass:/var/ossec/etc/authd.pass
